name: SyncingFeeling
main: net.LoadingChunks.SyncingFeeling.SyncingFeeling
version: 0.8.1

commands:
   sync:
      description: Sync Inventory
      usage: /sync
   sf:
      description: SyncingFeeling Admin
      usage: /sync <syncall|debug>
